from _ssh_helper import run
# As ubuntu, podman is the rootless container manager
print("=== podman ps ===")
rc,out,err=run("podman ps --format '{{.Names}}|{{.Image}}|{{.Ports}}' 2>&1 | head -30", timeout=20)
print(out)
print("---")
print("\n=== inspect gateway-nginx ===")
rc,out,err=run("podman inspect gateway-nginx --format '{{.HostConfig.Binds}}' 2>&1", timeout=10)
print("Binds:", out)
print("---")
rc,out,err=run("podman inspect gateway-nginx --format '{{json .Mounts}}' 2>&1 | head -50", timeout=10)
print("Mounts:", out)
print("---")
print("\n=== ls inside gateway ===")
rc,out,err=run("podman exec gateway-nginx ls /etc/nginx/conf.d/ 2>&1", timeout=10)
print(out)
print("\n=== gateway routes dir ===")
rc,out,err=run("podman exec gateway-nginx sh -c 'ls /etc/nginx/conf.d/routes/ 2>&1 || echo NORDIR' 2>&1", timeout=10)
print(out)
print("\n=== Check default.conf for include ===")
rc,out,err=run("podman exec gateway-nginx cat /etc/nginx/conf.d/default.conf 2>&1 | head -100", timeout=10)
print(out)
