#!/usr/bin/env node
// PRD-442 三端 token 生成脚本（单一真相源 → H5 css / 小程序 wxss / Flutter dart）
// 用法：node scripts/gen-tokens.mjs
// 重要：本脚本输出的三端文件全部由本脚本 100% 生成，开发者不应手动修改。
//      CI 校验：脚本运行后 git diff 必须为空，否则阻断合并。

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const TOKENS_PATH = resolve(ROOT, 'design-system', 'design-tokens.json');
const OUT_CSS  = resolve(ROOT, 'h5-web', 'public', 'design-system-v2', 'design-tokens.css');
const OUT_WXSS = resolve(ROOT, 'miniprogram', 'styles', 'design-tokens.wxss');
const OUT_DART = resolve(ROOT, 'packages', 'bini_design_tokens', 'lib', 'src', 'tokens.g.dart');

const HEADER_AUTO = (target) =>
  `/* AUTO-GENERATED by scripts/gen-tokens.mjs — DO NOT EDIT MANUALLY.\n` +
  `   Single source of truth: design-system/design-tokens.json\n` +
  `   Target: ${target}\n` +
  `   Run \`node scripts/gen-tokens.mjs\` after editing the JSON. */\n\n`;

function ensureDir(filePath) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function genCss(tokens) {
  const lines = [];
  lines.push(HEADER_AUTO('H5 (CSS Custom Properties)'));
  lines.push(':root {');

  // Colors
  lines.push('  /* ===== Color: brand (sky blue 11 levels) ===== */');
  for (const [k, v] of Object.entries(tokens.color.brand)) {
    lines.push(`  --color-brand-${k}: ${v.value};`);
  }
  lines.push('  /* ===== Color: text ===== */');
  for (const [k, v] of Object.entries(tokens.color.text)) {
    lines.push(`  --color-text-${k}: ${v.value};`);
  }
  lines.push('  /* ===== Color: bg ===== */');
  for (const [k, v] of Object.entries(tokens.color.bg)) {
    lines.push(`  --color-bg-${k}: ${v.value};`);
  }
  lines.push('  /* ===== Color: semantic (allowed scenarios only — see PRD-442 §7) ===== */');
  for (const [k, v] of Object.entries(tokens.color.semantic)) {
    lines.push(`  --color-${k}: ${v.value};`);
  }

  lines.push('  /* ===== Gradient ===== */');
  for (const [k, v] of Object.entries(tokens.gradient)) {
    const cssName = k.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
    lines.push(`  --gradient-${cssName}: ${v.value};`);
  }

  lines.push('  /* ===== Font Size ===== */');
  for (const [k, v] of Object.entries(tokens.fontSize)) {
    lines.push(`  --fs-${k}: ${v.value}${v.unit};`);
  }

  lines.push('  /* ===== Spacing ===== */');
  for (const [k, v] of Object.entries(tokens.space)) {
    lines.push(`  --sp-${k}: ${v.value}${v.unit};`);
  }

  lines.push('  /* ===== Radius ===== */');
  for (const [k, v] of Object.entries(tokens.radius)) {
    lines.push(`  --radius-${k}: ${v.value}${v.unit};`);
  }

  lines.push('  /* ===== Shadow (sky blue only — black forbidden) ===== */');
  for (const [k, v] of Object.entries(tokens.shadow)) {
    if (k === 'comment') continue;
    lines.push(`  --shadow-${k}: ${v.value};`);
  }

  lines.push('  /* ===== Duration ===== */');
  for (const [k, v] of Object.entries(tokens.duration)) {
    lines.push(`  --duration-${k}: ${v.value}${v.unit};`);
  }

  lines.push('  /* ===== Easing ===== */');
  for (const [k, v] of Object.entries(tokens.easing)) {
    lines.push(`  --easing-${k}: ${v.value};`);
  }

  lines.push('}');
  lines.push('');
  // 病历卡铁律组件
  lines.push('/* ===== PRD-442 iron rule: medical card ===== */');
  lines.push('.bh-card-medical {');
  lines.push('  background: var(--color-bg-base);');
  lines.push('  border-radius: var(--radius-lg);');
  lines.push('  box-shadow: var(--shadow-2);');
  lines.push('  padding: var(--sp-4);');
  lines.push('  position: relative;');
  lines.push('}');
  lines.push('.bh-card-medical::before {');
  lines.push('  content: "";');
  lines.push('  position: absolute;');
  lines.push('  top: 0; bottom: 0; left: 0;');
  lines.push('  width: 3px;');
  lines.push('  background: var(--color-brand-400);');
  lines.push('  border-top-left-radius: var(--radius-lg);');
  lines.push('  border-bottom-left-radius: var(--radius-lg);');
  lines.push('}');
  lines.push('');
  lines.push('.bh-btn-primary {');
  lines.push('  background: var(--gradient-primary-btn);');
  lines.push('  color: var(--color-text-inverse);');
  lines.push('  border: 0;');
  lines.push('  border-radius: var(--radius-lg);');
  lines.push('  min-height: 44px;');
  lines.push('  padding: 0 var(--sp-5);');
  lines.push('  font-size: var(--fs-md);');
  lines.push('  box-shadow: var(--shadow-2);');
  lines.push('  cursor: pointer;');
  lines.push('  transition: opacity var(--duration-fast) var(--easing-standard);');
  lines.push('}');
  lines.push('.bh-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }');
  lines.push('');
  return lines.join('\n');
}

function genWxss(tokens) {
  // 小程序 WXSS：CSS 变量 + rpx 单位（设计单位 px → rpx 自动 ×2）
  const toRpx = (v) => `${v * 2}rpx`;
  const lines = [];
  lines.push(HEADER_AUTO('Mini Program (WXSS, rpx units)'));
  lines.push('page {');
  for (const [k, v] of Object.entries(tokens.color.brand)) {
    lines.push(`  --color-brand-${k}: ${v.value};`);
  }
  for (const [k, v] of Object.entries(tokens.color.text)) {
    lines.push(`  --color-text-${k}: ${v.value};`);
  }
  for (const [k, v] of Object.entries(tokens.color.bg)) {
    lines.push(`  --color-bg-${k}: ${v.value};`);
  }
  for (const [k, v] of Object.entries(tokens.color.semantic)) {
    lines.push(`  --color-${k}: ${v.value};`);
  }
  for (const [k, v] of Object.entries(tokens.gradient)) {
    const name = k.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
    lines.push(`  --gradient-${name}: ${v.value};`);
  }
  for (const [k, v] of Object.entries(tokens.fontSize)) {
    lines.push(`  --fs-${k}: ${toRpx(v.value)};`);
  }
  for (const [k, v] of Object.entries(tokens.space)) {
    lines.push(`  --sp-${k}: ${toRpx(v.value)};`);
  }
  for (const [k, v] of Object.entries(tokens.radius)) {
    if (v.value === 9999) lines.push(`  --radius-${k}: 9999rpx;`);
    else lines.push(`  --radius-${k}: ${toRpx(v.value)};`);
  }
  for (const [k, v] of Object.entries(tokens.shadow)) {
    if (k === 'comment') continue;
    lines.push(`  --shadow-${k}: ${v.value};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('.bh-card-medical {');
  lines.push('  background: var(--color-bg-base);');
  lines.push('  border-radius: var(--radius-lg);');
  lines.push('  box-shadow: var(--shadow-2);');
  lines.push('  padding: var(--sp-4);');
  lines.push('  position: relative;');
  lines.push('}');
  lines.push('.bh-card-medical::before {');
  lines.push('  content: "";');
  lines.push('  position: absolute;');
  lines.push('  top: 0; bottom: 0; left: 0;');
  lines.push('  width: 6rpx;');
  lines.push('  background: var(--color-brand-400);');
  lines.push('}');
  lines.push('');
  lines.push('.bh-btn-primary {');
  lines.push('  background: var(--gradient-primary-btn);');
  lines.push('  color: var(--color-text-inverse);');
  lines.push('  border: 0;');
  lines.push('  border-radius: var(--radius-lg);');
  lines.push('  min-height: 88rpx;');
  lines.push('  font-size: var(--fs-md);');
  lines.push('}');
  return lines.join('\n');
}

function dartConst(name, hex) {
  // hex like '#38bdf8' -> Color(0xFF38BDF8)
  const v = hex.replace('#', '').toUpperCase();
  return `  static const ${name} = Color(0xFF${v});`;
}

function genDart(tokens) {
  const lines = [];
  lines.push(`// AUTO-GENERATED by scripts/gen-tokens.mjs — DO NOT EDIT MANUALLY.`);
  lines.push(`// Single source of truth: design-system/design-tokens.json`);
  lines.push(`// Run \`node scripts/gen-tokens.mjs\` after editing the JSON.`);
  lines.push('');
  lines.push("import 'package:flutter/material.dart';");
  lines.push('');
  lines.push('/// PRD-442 全域天蓝色阶（与 H5 / 小程序 hex 完全一致）。');
  lines.push('class BhTokens {');
  lines.push('  BhTokens._();');
  lines.push('');
  for (const [k, v] of Object.entries(tokens.color.brand)) {
    lines.push(dartConst(`colorBrand${k}`, v.value));
  }
  lines.push('');
  for (const [k, v] of Object.entries(tokens.color.text)) {
    const cap = k.charAt(0).toUpperCase() + k.slice(1);
    lines.push(dartConst(`colorText${cap}`, v.value));
  }
  for (const [k, v] of Object.entries(tokens.color.bg)) {
    const cap = k.charAt(0).toUpperCase() + k.slice(1);
    lines.push(dartConst(`colorBg${cap}`, v.value));
  }
  for (const [k, v] of Object.entries(tokens.color.semantic)) {
    const cap = k.charAt(0).toUpperCase() + k.slice(1);
    lines.push(dartConst(`color${cap}`, v.value));
  }
  lines.push('');
  // Font size
  for (const [k, v] of Object.entries(tokens.fontSize)) {
    const safeKey = k.replace(/[^a-zA-Z0-9]/g, '');
    const name = isNaN(parseInt(k.charAt(0))) ? safeKey : 'size' + safeKey;
    lines.push(`  static const double fs${name.charAt(0).toUpperCase() + name.slice(1)} = ${v.value}.0;`);
  }
  lines.push('');
  for (const [k, v] of Object.entries(tokens.space)) {
    lines.push(`  static const double sp${k} = ${v.value}.0;`);
  }
  lines.push('');
  for (const [k, v] of Object.entries(tokens.radius)) {
    const safeKey = k.replace(/[^a-zA-Z0-9]/g, '');
    const name = isNaN(parseInt(k.charAt(0))) ? safeKey : 'r' + safeKey;
    lines.push(`  static const double radius${name.charAt(0).toUpperCase() + name.slice(1)} = ${v.value}.0;`);
  }
  lines.push('');
  for (const [k, v] of Object.entries(tokens.duration)) {
    const cap = k.charAt(0).toUpperCase() + k.slice(1);
    lines.push(`  static const Duration duration${cap} = Duration(milliseconds: ${v.value});`);
  }
  lines.push('}');
  lines.push('');
  // Gradients
  lines.push('class BhGradients {');
  lines.push('  BhGradients._();');
  lines.push('');
  for (const [k, v] of Object.entries(tokens.gradient)) {
    const m = v.value.match(/#[0-9a-fA-F]{6}/g) || [];
    const colorStops = m.map(c => `Color(0xFF${c.replace('#','').toUpperCase()})`).join(', ');
    lines.push(`  static const ${k} = LinearGradient(`);
    lines.push(`    begin: Alignment.topLeft,`);
    lines.push(`    end: Alignment.bottomRight,`);
    lines.push(`    colors: [${colorStops}],`);
    lines.push(`  );`);
  }
  lines.push('}');
  lines.push('');
  // Shadows
  lines.push('class BhShadows {');
  lines.push('  BhShadows._();');
  lines.push('');
  // Hard-code 4 levels with fixed alpha → const Color
  const shadowAlpha = { '1': 0x14, '2': 0x1A, '3': 0x1F, '4': 0x29 };
  for (const k of ['1','2','3','4']) {
    const blur = { '1': 2, '2': 8, '3': 16, '4': 32 }[k];
    const yOff = { '1': 1, '2': 2, '3': 4, '4': 8 }[k];
    const a = shadowAlpha[k].toString(16).toUpperCase().padStart(2,'0');
    lines.push(`  static const List<BoxShadow> shadow${k} = [BoxShadow(color: Color(0x${a}38BDF8), offset: Offset(0, ${yOff}), blurRadius: ${blur})];`);
  }
  lines.push('}');
  return lines.join('\n');
}

function main() {
  const raw = readFileSync(TOKENS_PATH, 'utf-8');
  const tokens = JSON.parse(raw);

  ensureDir(OUT_CSS);
  ensureDir(OUT_WXSS);
  ensureDir(OUT_DART);

  writeFileSync(OUT_CSS,  genCss(tokens),  'utf-8');
  writeFileSync(OUT_WXSS, genWxss(tokens), 'utf-8');
  writeFileSync(OUT_DART, genDart(tokens), 'utf-8');

  console.log('[gen-tokens] OK:');
  console.log('  -', OUT_CSS);
  console.log('  -', OUT_WXSS);
  console.log('  -', OUT_DART);
}

main();
