#!/usr/bin/env node
// PRD-442 三端图标组件生成脚本
// 输入：design-system/icons/*.svg
// 输出：
//   - h5-web/public/design-system-v2/icons.json  （SVG 内容 map，供 H5 BhIcon 组件按需消费）
//   - miniprogram/styles/icons.json              （同上，供小程序 bh-icon 组件消费）
//   - packages/bini_design_tokens/lib/src/icons.g.dart  （Flutter SvgPicture.string map）

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const ICONS_DIR = resolve(ROOT, 'design-system', 'icons');
const OUT_H5  = resolve(ROOT, 'h5-web',       'public', 'design-system-v2', 'icons.json');
const OUT_MP  = resolve(ROOT, 'miniprogram',  'styles', 'icons.json');
const OUT_DART = resolve(ROOT, 'packages', 'bini_design_tokens', 'lib', 'src', 'icons.g.dart');

const ensureDir = (p) => { const d = dirname(p); if (!existsSync(d)) mkdirSync(d, { recursive: true }); };

function loadIcons() {
  if (!existsSync(ICONS_DIR)) return {};
  const files = readdirSync(ICONS_DIR).filter(f => f.endsWith('.svg'));
  const map = {};
  for (const f of files) {
    const name = basename(f, '.svg');
    const content = readFileSync(resolve(ICONS_DIR, f), 'utf-8').replace(/\r?\n/g, '').trim();
    map[name] = content;
  }
  return map;
}

function main() {
  const icons = loadIcons();
  const names = Object.keys(icons).sort();

  ensureDir(OUT_H5);
  ensureDir(OUT_MP);
  ensureDir(OUT_DART);

  const header = {
    '$comment': 'AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT MANUALLY.',
    '$source': 'design-system/icons/',
    '$count': names.length,
  };
  const payload = JSON.stringify({ ...header, icons }, null, 2);
  writeFileSync(OUT_H5, payload, 'utf-8');
  writeFileSync(OUT_MP, payload, 'utf-8');

  // Dart icons map
  const lines = [];
  lines.push(`// AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT MANUALLY.`);
  lines.push(`// Source: design-system/icons/  (count: ${names.length})`);
  lines.push('');
  lines.push('class BhIcons {');
  lines.push('  BhIcons._();');
  lines.push('');
  lines.push('  static const Map<String, String> svgMap = {');
  for (const n of names) {
    const escaped = icons[n].replace(/\\/g,'\\\\').replace(/'/g,"\\'");
    lines.push(`    '${n}': '${escaped}',`);
  }
  lines.push('  };');
  lines.push('');
  lines.push('  static const List<String> names = [');
  for (const n of names) lines.push(`    '${n}',`);
  lines.push('  ];');
  lines.push('}');
  writeFileSync(OUT_DART, lines.join('\n'), 'utf-8');

  console.log(`[gen-icons] generated ${names.length} icons:`);
  for (const n of names) console.log('  -', n);
}

main();
