// AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT MANUALLY.
// Source: design-system/icons/  (count: 8)

class BhIcons {
  BhIcons._();

  static const Map<String, String> svgMap = {
    'bell': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <path d="M6 9a6 6 0 0 1 12 0v4l1.5 3h-15L6 13V9z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>  <path d="M10 19a2 2 0 0 0 4 0" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>  <path d="M6 9a6 6 0 0 1 12 0v4l1.5 3h-15L6 13V9z" fill="#bae6fd" opacity="0.4"/></svg>',
    'camera': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <path d="M3 8h4l2-3h6l2 3h4a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>  <circle cx="12" cy="13" r="3.5" stroke="currentColor" stroke-width="1.5"/>  <circle cx="12" cy="13" r="3.5" fill="#bae6fd" opacity="0.4"/></svg>',
    'chevron-down': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    'family': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <circle cx="9" cy="8" r="3" stroke="currentColor" stroke-width="1.5"/>  <circle cx="17" cy="9" r="2.5" stroke="currentColor" stroke-width="1.5"/>  <path d="M3 19v-1a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>  <path d="M15 19v-1a3 3 0 0 1 3-3h1a3 3 0 0 1 3 3v1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>  <circle cx="9" cy="8" r="3" fill="#bae6fd" opacity="0.4"/></svg>',
    'health-report': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <path d="M7 3h8l4 4v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>  <path d="M14 3v4h5" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>  <path d="M8 13l2-2 2 2 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>  <rect x="8" y="16" width="8" height="1.5" rx="0.5" fill="#bae6fd"/></svg>',
    'heart-rate': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <path d="M3 12h4l2-5 4 10 2-5h6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>  <path d="M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10z" stroke="#bae6fd" stroke-width="1.2" opacity="0.6"/></svg>',
    'medication': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <rect x="3" y="9" width="18" height="6" rx="3" stroke="currentColor" stroke-width="1.5"/>  <line x1="12" y1="9" x2="12" y2="15" stroke="currentColor" stroke-width="1.5"/>  <rect x="3" y="9" width="9" height="6" rx="3" fill="#bae6fd" opacity="0.5"/></svg>',
    'voice': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">  <rect x="9" y="3" width="6" height="12" rx="3" stroke="currentColor" stroke-width="1.5"/>  <path d="M5 11a7 7 0 0 0 14 0" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>  <line x1="12" y1="18" x2="12" y2="21" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>  <rect x="9" y="3" width="6" height="12" rx="3" fill="#bae6fd" opacity="0.4"/></svg>',
  };

  static const List<String> names = [
    'bell',
    'camera',
    'chevron-down',
    'family',
    'health-report',
    'heart-rate',
    'medication',
    'voice',
  ];
}