// AUTO-GENERATED by scripts/gen-tokens.mjs — DO NOT EDIT MANUALLY.
// Single source of truth: design-system/design-tokens.json
// Run `node scripts/gen-tokens.mjs` after editing the JSON.

import 'package:flutter/material.dart';

/// PRD-442 全域天蓝色阶（与 H5 / 小程序 hex 完全一致）。
class BhTokens {
  BhTokens._();

  static const colorBrand50 = Color(0xFFF0F9FF);
  static const colorBrand100 = Color(0xFFE0F2FE);
  static const colorBrand150 = Color(0xFFDBEAFE);
  static const colorBrand200 = Color(0xFFBAE6FD);
  static const colorBrand300 = Color(0xFF7DD3FC);
  static const colorBrand400 = Color(0xFF38BDF8);
  static const colorBrand500 = Color(0xFF0EA5E9);
  static const colorBrand600 = Color(0xFF0284C7);
  static const colorBrand700 = Color(0xFF0369A1);
  static const colorBrand800 = Color(0xFF075985);
  static const colorBrand900 = Color(0xFF0C4A6E);

  static const colorTextPrimary = Color(0xFF1F2937);
  static const colorTextSecondary = Color(0xFF6B7280);
  static const colorTextTertiary = Color(0xFF9CA3AF);
  static const colorTextInverse = Color(0xFFFFFFFF);
  static const colorBgBase = Color(0xFFFFFFFF);
  static const colorBgSoft = Color(0xFFF9FAFB);
  static const colorBgSubtle = Color(0xFFF0F9FF);
  static const colorSuccess = Color(0xFF22C55E);
  static const colorWarning = Color(0xFFFBBF24);
  static const colorDanger = Color(0xFFEF4444);
  static const colorMember = Color(0xFFD4AF37);

  static const double fsXs = 12.0;
  static const double fsSm = 14.0;
  static const double fsMd = 16.0;
  static const double fsLg = 18.0;
  static const double fsXl = 20.0;
  static const double fsSize2xl = 22.0;
  static const double fsSize3xl = 24.0;
  static const double fsSize4xl = 28.0;
  static const double fsSize5xl = 36.0;

  static const double sp1 = 4.0;
  static const double sp2 = 8.0;
  static const double sp3 = 12.0;
  static const double sp4 = 16.0;
  static const double sp5 = 20.0;
  static const double sp6 = 24.0;
  static const double sp8 = 32.0;
  static const double sp10 = 40.0;
  static const double sp12 = 48.0;

  static const double radiusXs = 4.0;
  static const double radiusSm = 6.0;
  static const double radiusMd = 8.0;
  static const double radiusLg = 12.0;
  static const double radiusXl = 16.0;
  static const double radiusR2xl = 24.0;
  static const double radiusFull = 9999.0;

  static const Duration durationInstant = Duration(milliseconds: 100);
  static const Duration durationFast = Duration(milliseconds: 180);
  static const Duration durationBase = Duration(milliseconds: 240);
  static const Duration durationSlow = Duration(milliseconds: 360);
}

class BhGradients {
  BhGradients._();

  static const topbar = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFFF0F9FF), Color(0xFFDBEAFE)],
  );
  static const userBubble = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF7DD3FC), Color(0xFF38BDF8)],
  );
  static const primaryBtn = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF38BDF8), Color(0xFF0284C7)],
  );
  static const heroDeep = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF0369A1), Color(0xFF0C4A6E)],
  );
  static const userCard = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFFF0F9FF), Color(0xFFE0F2FE)],
  );
}

class BhShadows {
  BhShadows._();

  static const List<BoxShadow> shadow1 = [BoxShadow(color: Color(0x1438BDF8), offset: Offset(0, 1), blurRadius: 2)];
  static const List<BoxShadow> shadow2 = [BoxShadow(color: Color(0x1A38BDF8), offset: Offset(0, 2), blurRadius: 8)];
  static const List<BoxShadow> shadow3 = [BoxShadow(color: Color(0x1F38BDF8), offset: Offset(0, 4), blurRadius: 16)];
  static const List<BoxShadow> shadow4 = [BoxShadow(color: Color(0x2938BDF8), offset: Offset(0, 8), blurRadius: 32)];
}